### ISSUE TITLE
ДЗ№3, Белоусов Даниил, УТС-21

### ISSUE THREAD

**Issue by Daniiltoo** [MIEE-ACS/domashnee-zadanie-no3-Daniiltoo#1]
Задание выполнено

**Comment by d-makarenko** [comment]
1. При запуске приложение отображает некорректные ответы.
2. В строке "Упражнение Х..." Х - это правильный ответ. Как то странно его отображать. Туда было бы правильнее выводить переменную Counter, в ней как раз хранится номер.
3. Если правильный вариант выпадает на четвертую позицию, то приложение "зависает" и перестает генерировать новые задания.

В следующий раз прошу проверять корректность работы самостоятельно. Если непонятно как сделать что-то, то я могу подсказать, а сдавать практически неработающее задание - это неправильно.

**Comment by d-makarenko** [comment]
К тому же задание было скопировано у Кадырова.

**Comment by Daniiltoo** [comment]
Ну ладно, спасибо за ответ☺️
--
Отправлено из Mail.ru для Android воскресенье, 03 ноября 2019г., 20:48 +03:00 от Dmitry Makarenko  notifications@github.com :
